# Site settings
title: "Gregory Tomy Resume"
# description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Gregory Tomy"
resume_title:                   "Master's in Applied Mathematics"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "gregory.tomy@colorado.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "917-428-6003"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "Boulder, Colorado • 917-428-6003 • gregory.tomy@colorado.edu"
display_header_contact_info:    "false"

resume_header_intro: "<p>With roots in investment banking and a focus now on Applied Mathematics, I am uniquely positioned at the intersection of business and data science. My mission: to evolve as a Machine Learning Engineer, driving business growth through data-driven insights</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/GregoryTomy"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/gregorytomy/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "hthttps://gregorytomy.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
